config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controller: {
      sessions: 'users/sessions'
  }

  devise_scope :user do
    post 'users/guest_admin_sign_in', to: 'users/sessions#guest_admin_sign_in'
    post 'users/guest_executive_sign_in', to: 'users/sessions#guest_executive_sign_in'
    post 'users/guest_general_sign_in', to: 'users/sessions#guest_general_sign_in'
  end

  root 'tops#index'
  resources :users
  resources :schools
  resources :favorites
  #root 'schools#index' 
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :trackable, :validatable
  has_many :schools
  has_many :favorites, dependent: :destroy
  has_many :favorite_schools, through: :favorites, source: :school
  validates :name, presence: true
  validates :email, presence: true
  enum role: { general: 0, executive: 1 }

  def role_i18n
    I18n.t("enums.user.role.#{role}")
  end

  def self.guest_admin
    find_or_create_by!(email: 'guest_admin@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "ゲストユーザー(管理者)"
      user.admin = "admin"
    end
  end

  def self.guest_executive
    find_or_create_by!(email: 'guest_executive@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "ゲストユーザー(経営者)"
      user.role = "executive"
    end
  end 

  def self.guest_general
    find_or_create_by!(email: 'guest_general@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "ゲストユーザー(一般ユーザー)"
      user.role = "general"
    end
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
    def create
      build_resource(sign_up_params)

      resource.save
      yield resource if block_given?
      if resource.persisted?
        set_flash_message! :notice, :signed_up
        sign_up(resource_name, resource)
        respond_with resource, location: after_sign_up_path_for(resource)
      else
        clean_up_passwords resource
        set_minimum_password_length
        respond_with resource
      end
    end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
    def configure_account_update_params
      devise_parameter_sanitizer.permit(:account_update, keys: [:name, :role])
    end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  private

  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :role)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
  def guest_admin_sign_in
    user = User.guest_admin
    sign_in user
    redirect_to user_path(current_user.id), notice: 'ゲスト管理者ユーザーとしてログインしました。'
  end

  def guest_executive_sign_in
    user = User.guest_executive
    sign_in user
    redirect_to user_path(current_user.id), notice: 'ゲスト（経営者）ユーザーとしてログインしました。'
  end

  def guest_general_sign_in
    user = User.guest_general
    sign_in user
    redirect_to user_path(current_user.id), notice: 'ゲスト一般ユーザーとしてログインしました。'
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  

  def show
    @user = User.find(params[:id])
    if current_user.role == "executive"
      @schools = current_user.schools.page(params[:page]).per(5)
    else  
      @favorite_schools = current_user.favorite_schools.page(params[:page]).per(5)
    end
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render "edit"
    else
      redirect_to users_path
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "プロフィールを編集しました！"
    else
      flash.now[:danger] = "プロフィールを更新できませんでした"
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<%= stylesheet_link_tag 'users' %>

<div class="detail-container">
  <div class="detail-item">
    <div class="image-info">
      <h1><%= @user.name %>さんのプロフィール編集</h1>

      <%= form_with model: @user, local: true do |f| %>
        <div class="field">
          <%= f.label :name %>
          <%= f.text_field :name, class: 'form-control mb-3' %>
        </div>

        <div class="field">
          <%= f.label :email %>
          <%= f.email_field :email, class: 'form-control mb-3' %>
        </div>

        <div class="field">
          <%= f.label :password %>
          <%= f.text_field :password %>
        </div>

        <div class="field">
          <%= f.label :password_confirmation %>
          <%= f.text_field :password_confirmation %>
        </div>

        <%= f.submit "更新", class: "submit-button"%>
      <%end%>
      <%= link_to 'プロフィールに戻る', user_path(current_user.id), class: "submit-button" %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<head>
  <%= stylesheet_link_tag 'users_show' %>
</head>

<h1><%= @user.name %>さんのページ</h1>
      
<p>メールアドレス: <%= @user.email %></p>

<br>

<div class="profile">
  <% if @user == current_user %>
    <%= link_to "プロフィールの編集", edit_user_path %>
  <% end %>
</div>

<br>

<div class="okiniiri">
  <% if current_user.role == "executive" %>
    <h3>塾投稿一覧</h3>
  <% else %>
    <h3>お気に入り一覧</h3>
  <%end%>
</div>


<% if current_user.role == "executive" %>
  <%= paginate @schools %>
<% else %>  
  <%= paginate @favorite_schools %>
<% end %>  



<table class="custom-table">
  <thead>
    <tr>
      <th>塾名</th>
      <th>概要</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% if current_user.role == "executive" %>
      <% @schools.each do |school| %>
            <tr>
              <td><%= school.name %></td>
              <td><%= school.overview %></td>
              <td><button type="button" class="btn-secondary"><%= link_to '編集', edit_school_path(school) %></button></td>
              <td><button type="button" class="btn-tertiary"><%= link_to '削除', school, method: :delete, data: { confirm: 'Are you sure?' } %></button></td>
            </tr>
      <% end %>
    <% else %>
      <% @favorite_schools.each do |school| %>
        <% favorite = current_user.favorites.find_by(school_id: school.id) %>
          <tr>
            <td><%= school.name %></td>
            <td><%= school.overview %></td>
            <td><button type="button" class="btn-secondary"><%= link_to '詳細', school_path(school.id) %></button></td>
            <% if favorite.present? %>
              <td><%= link_to 'お気に入り解除する', favorite_path(id: favorite.id), method: :delete, class: 'btn btn-danger' %></td>
            <% else %>
              <td>お気に入り情報がありません</td>
            <% end %>
          </tr>
      <% end %>
    <% end %>
  </tbody>
</table>