config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controller: {
      sessions: 'users/sessions'
  }

  devise_scope :user do
    post 'users/guest_admin_sign_in', to: 'users/sessions#guest_admin_sign_in'
    post 'users/guest_executive_sign_in', to: 'users/sessions#guest_executive_sign_in'
    post 'users/guest_general_sign_in', to: 'users/sessions#guest_general_sign_in'
  end

  root 'tops#index'
  resources :users
  resources :schools
  resources :favorites
  #root 'schools#index' 
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/school.rb
class School < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
  has_many :handlings, dependent: :destroy
  has_many :subjects, through: :handlings, source: :subject
  has_one_attached :image
  validates :name, presence: true
  validates :prefecture, presence: true
  validates :city, presence: true
  validates :name, presence: true
  validates :phone, presence: true
  validates :overview, presence: true, length: { maximum: 200 }
  validates :image, presence: true


  def self.ransackable_attributes(auth_object = nil)
    %w(id name prefecture city phone overview image created_at updated_at subject_id)
  end
  
  def self.ransackable_associations(auth_object = nil)
    %w(subjects)
  end
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  before_action :set_school, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, only: [:new, :create]

  # GET /schools or /schools.json
  def index
    @q = School.ransack(params[:q])
    @schools = @q.result(distinct: true).includes(:subjects).page(params[:page]).per(10)
  end

  # GET /schools/1 or /schools/1.json
  def show
    if current_user
      @favorite = current_user.favorites.find_by(school_id: @school.id)
    else
      redirect_to new_user_session_path
    end  
  end

  # GET /schools/new
  def new
    if current_user.role == "executive"
      @school = School.new
    else current_user.role == "general"
      redirect_to(schools_path)
    end  
  end

  # GET /schools/1/edit
  def edit
  end

  # POST /schools or /schools.json
  def create
    @school = current_user.schools.build(school_params)
    respond_to do |format|
      #if @school.image.present?
        if @school.save
          format.html { redirect_to school_url(@school), notice: "School was successfully created." }
          format.json { render :show, status: :created, location: @school }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @school.errors, status: :unprocessable_entity }
        end
      #end  
    end
  end

  # PATCH/PUT /schools/1 or /schools/1.json
  def update
    respond_to do |format|
      if @school.update(school_params)
        format.html { redirect_to school_url(@school), notice: "School was successfully updated." }
        format.json { render :show, status: :ok, location: @school }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schools/1 or /schools/1.json
  def destroy
    @school.destroy

    respond_to do |format|
      format.html { redirect_to schools_url, notice: "School was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
  
    # Use callbacks to share common setup or constraints between actions.
  def set_school
    @school = School.find(params[:id])
  end

    # Only allow a list of trusted parameters through.
  def school_params
    params.require(:school).permit(:name, :prefecture, :city, :phone, :overview, :image, :id, { subject_ids: [] })
  end
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/views/schools/_form.html.erb
<%= form_with(model: school) do |form| %>
  <% if school.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(school.errors.count, "") %> 件のエラーが検出されました:</h2>

      <ul>
        <% school.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <%= stylesheet_link_tag 'schools_form' %>
  

    <%= form.label :塾名 %>
    <%= form.text_field :name, class: 'form-control', placeholder: "○○塾"  %>

  <br>

    <%= form.label :県名 %>
    <%= form.text_field :prefecture, class: 'form-control', placeholder: "○○県" %>

  <br>

    <%= form.label :住所 %>
    <%= form.text_field :city, class: 'form-control', placeholder: "○○市" %>

  <br>

    <%= form.label :電話番号 %>
    <%= form.text_field :phone, class: 'form-control', placeholder: "078000111" %>

  <br>

    <%= form.label :概要 %>
    <%= form.text_area :overview, class: 'form-control', placeholder: "個人経営で、生徒との距離感を大切にしています" %>

  <br>

  <div class="field">
    <%= form.label :科目 %>
    <%= form.collection_check_boxes(:subject_ids, Subject.all, :id, :name) do |cd| %>
      <%= cd.label { cd.check_box + cd.text } %>
    <% end %>
  </div>

  <br>

  <%= form.file_field :image %>

  <br>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/schools/edit.html.erb
<h1>塾編集ページ</h1>

<%= render 'form', school: @school %>
<%= stylesheet_link_tag 'schools_form' %>
<br>

<td><button type="button" class="btn-secondary"><%= link_to '詳細', @school %></button>
<td><button type="button" class="btn-secondary"><%= link_to '戻る', schools_path %></button>

app/views/schools/index.html.erb
<head>
  <%= stylesheet_link_tag 'schools' %>
</head>

<table>
  <tr>
    <td><h3>塾検索</h3><td>
    <% if current_user && current_user.role == "executive"%>
      <td><button type="button" class="btn-secondary"><%= link_to '塾の新規投稿', new_school_path %></button><td>
    <% end %>
    <% if current_user %>
      <td><button type="button" class="btn-secondary"><%= link_to 'マイページ', user_path(current_user) %></button><td>
    <% end %>  
  </tr>
</table> 

<%= search_form_for @q, url: schools_path do |f| %>
  <%= f.label :name_cont, '塾名' %>
  <%= f.search_field :name_cont, placeholder: "○○塾" %>
  <%= f.label :prefecture_cont, '都道府県' %>
  <%= f.search_field :prefecture_cont, placeholder: "○○県" %>
  <div class="check_box">
    <%= f.label :subjects_id_eq_any, '履修科目' %>
    <%= f.collection_check_boxes :subjects_id_eq_any, Subject.all, :id, :name %>
  </div>
  <%= f.submit '検索' %>
<% end %>



<h3>塾一覧</h3>

<%= paginate @schools, thema: 'twitter-bootstrap-4' %>

<table>
  <tbody>
    <div class="school-cards">
      <% @schools.each do |school| %>
        <div class="school-card">
            <p>
              <% if school.image.attached? %>
                  <%= image_tag school.image.variant(gravity: "Center", resize: "100x100!", crop: "100x100+0+0").processed %>
              <% end %>
            </p>
            <p><%= school.name %></p>
            <p><%= school.prefecture %></p>
            <p><%= school.city %></p>
            <p>
              <% school.subjects.each do |subject| %>
                <%= subject.name %>
              <% end %>
            </p>
            <p><%= link_to '詳細', school %></p>
        </div>  
      <% end %>
    </div>  
  </tbody>
</table>

app/views/schools/new.html.erb
<h1>塾新規作成</h1>

<%= render 'form', school: @school %>

<td><button type="button" class="btn-secondary"><%= link_to '戻る', schools_path %></button></td>

app/views/schools/show.html.erb
<head>
  <%= stylesheet_link_tag 'schools_show' %>
</head>

<div class="contents">
  <div class="content">
    <p>
      <strong>塾名:</strong>
      <%= @school.name %>
    </p>

    <p>
      <strong>都道府県:</strong>
      <%= @school.prefecture %>
    </p>

    <p>
      <strong>住所:</strong>
      <%= @school.city %>
    </p>

    <p>
      <strong>電話番号:</strong>
      <%= @school.phone %>
    </p>

    <p>
      <strong>科目</strong>
        <% @school.subjects.each do |subject| %>
          <%= subject.name %>
        <% end %>
    </p>    

    <p>
      <strong>概要:</strong>
      <%= @school.overview %>
    </p>
    <br>
    <br>
    <p>
      <strong>画像:</strong>
      <br>
      <%= image_tag @school.image, size:'200x200' %>
    </p>
    
    <br>
    <br>

    <% if current_user.role == "general" %>
      <% unless @school.user_id == current_user.id %>
        <% if @favorite.present? %>
          <%= link_to 'お気に入り解除する', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-danger' %>
        <% else %>
          <%= link_to 'お気に入りする', favorites_path(school_id: @school.id), method: :post, class: 'btn btn-primary' %>
        <% end %>
      <% end %>
    <% end %>  
    
    <% if @school.user_id == current_user.id %>
      <%= link_to '編集', edit_school_path(@school) %> |
      <%= link_to '削除', @school, method: :delete, data: { confirm: 'Are you sure?' } %> |
    <% end %>

    <%= link_to '戻る', schools_path %> 
  </div>  
</div>