config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controller: {
      sessions: 'users/sessions'
  }

  devise_scope :user do
    post 'users/guest_admin_sign_in', to: 'users/sessions#guest_admin_sign_in'
    post 'users/guest_executive_sign_in', to: 'users/sessions#guest_executive_sign_in'
    post 'users/guest_general_sign_in', to: 'users/sessions#guest_general_sign_in'
  end

  root 'tops#index'
  resources :users
  resources :schools
  resources :favorites
  #root 'schools#index' 
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SchoolApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <div class="left">
        <h4> Search cram school</h4>
      </div>
      <div class="right">
        <% if user_signed_in? %>
            <% unless current_page?(schools_path) %>
              <%= link_to "塾一覧", schools_path %>
            <% end %>  
            <%= link_to 'ログアウト', destroy_user_session_path, method: :delete %>
              <% if current_user.admin? %>
                <%= link_to "管理者ページ", rails_admin_path %>
              <% end %>  
          <% else %>
            <% unless current_page?(schools_path) %>
              <%= link_to "塾一覧", schools_path %>
            <% end %>
            <%= link_to "新規登録", new_user_registration_path %>
            <%= link_to 'ログイン', new_user_session_path %>
          <% end %>
      </div>
    </header>
    

      <% if notice %>
        <p class="alert alert-notice"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-error"><%= alert %></p>
      <% end %>

      <%= yield %>


    <footer>
      <div class="footer">
        <p>© <%= Time.current.year %> DICcampany. All rights reserved.</p>
      </div>
    </footer>
  </body>
</html>